In [1]:
#Fatih Yanık - 20180301034

import numpy as np
import pandas as pd

In [2]:
dataframe = pd.read_csv('heart.csv')

In [3]:
dataframe

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M           ATA        140          289          0     Normal   
1     49   F           NAP        160          180          0     Normal   
2     37   M           ATA        130          283          0         ST   
3     48   F           ASY        138          214          0     Normal   
4     54   M           NAP        150          195          0     Normal   
..   ...  ..           ...        ...          ...        ...        ...   
913   45   M            TA        110          264          0     Normal   
914   68   M           ASY        144          193          1     Normal   
915   57   M           ASY        130          131          0     Normal   
916   57   F           ATA        130          236          0        LVH   
917   38   M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
1      156              N      1.0     Flat             1  
2       98              N      0.0       Up             0  
3      108              Y      1.5     Flat             1  
4      122              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0  

[918 rows x 12 columns]

In [4]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

dataframe['Sex'] = le.fit_transform(dataframe['Sex'])
dataframe['ExerciseAngina'] = le.fit_transform(dataframe['ExerciseAngina'])
dataframe['ChestPainType'] = le.fit_transform(dataframe['ChestPainType'])
dataframe['RestingECG'] = le.fit_transform(dataframe['RestingECG'])

dataframe

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0     40    1              1        140          289          0           1   
1     49    0              2        160          180          0           1   
2     37    1              1        130          283          0           2   
3     48    0              0        138          214          0           1   
4     54    1              2        150          195          0           1   
..   ...  ...            ...        ...          ...        ...         ...   
913   45    1              3        110          264          0           1   
914   68    1              0        144          193          1           1   
915   57    1              0        130          131          0           1   
916   57    0              1        130          236          0           0   
917   38    1              2        138          175          0           1   

     MaxHR  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172               0      0.0       Up             0  
1      156               0      1.0     Flat             1  
2       98               0      0.0       Up             0  
3      108               1      1.5     Flat             1  
4      122               0      0.0       Up             0  
..     ...             ...      ...      ...           ...  
913    132               0      1.2     Flat             1  
914    141               0      3.4     Flat             1  
915    115               1      1.2     Flat             1  
916    174               0      0.0     Flat             1  
917    173               0      0.0       Up             0  

[918 rows x 12 columns]

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X = dataframe.iloc[:, :-2].values
y = dataframe.iloc[:, -1].values

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3, random_state = 0, stratify = y)

In [8]:
from sklearn.preprocessing import StandardScaler
stdsc = StandardScaler()
X_train_std = stdsc.fit_transform(X_train)
X_test_std = stdsc.fit_transform(X_test)

In [9]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 3, metric = 'euclidean')
classifier.fit(X_train_std, y_train)

y_pred = classifier.predict(X_test_std)

In [10]:
from sklearn.metrics import confusion_matrix
confmat = confusion_matrix(y_test, y_pred)
confmat

array([[101,  22],
       [ 40, 113]], dtype=int64)

In [11]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.7753623188405797

In [12]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

In [13]:
knn3 = accuracy_score(y_test, y_pred)
knn3_p = precision_score(y_test, y_pred)
knn3_r = recall_score(y_test, y_pred)
knn3_f = f1_score(y_test, y_pred)

In [14]:
classifier = KNeighborsClassifier(n_neighbors = 7, metric = 'euclidean')
classifier.fit(X_train_std, y_train)

y_pred = classifier.predict(X_test_std)

In [15]:
confmat = confusion_matrix(y_test, y_pred)
confmat

array([[106,  17],
       [ 36, 117]], dtype=int64)

In [16]:
accuracy_score(y_test, y_pred)

0.8079710144927537

In [17]:
knn7 = accuracy_score(y_test, y_pred)
knn7_p = precision_score(y_test, y_pred)
knn7_r = recall_score(y_test, y_pred)
knn7_f = f1_score(y_test, y_pred)

In [18]:
classifier = KNeighborsClassifier(n_neighbors = 11, metric = 'euclidean')
classifier.fit(X_train_std, y_train)

y_pred = classifier.predict(X_test_std)

In [19]:
confmat = confusion_matrix(y_test, y_pred)
confmat

array([[110,  13],
       [ 30, 123]], dtype=int64)

In [20]:
accuracy_score(y_test, y_pred)

0.8442028985507246

In [21]:
knn11 = accuracy_score(y_test, y_pred)
knn11_p = precision_score(y_test, y_pred)
knn11_r = recall_score(y_test, y_pred)
knn11_f = f1_score(y_test, y_pred)

In [22]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import cross_val_score

import warnings
warnings.filterwarnings('ignore')

In [23]:
mlp1 = MLPClassifier(hidden_layer_sizes = (32,))
mlp1.fit(X_train, y_train)
accuracy1 = mlp1.score(X_test, y_test)
prediction1 = mlp1.predict(X_test)
mlp_1 = accuracy_score(y_test, prediction1)
mlp_1_p = precision_score(y_test, prediction1)
mlp_1_r = recall_score(y_test, prediction1)
mlp_1_f = f1_score(y_test, prediction1)

In [24]:
mlp_1

0.8188405797101449

In [25]:
mlp2 = MLPClassifier(hidden_layer_sizes = (32, 32))
mlp2.fit(X_train, y_train)
accuracy2 = mlp2.score(X_test, y_test)
prediction2 = mlp2.predict(X_test)
mlp_2 = accuracy_score(y_test, prediction2)
mlp_2_p = precision_score(y_test, prediction2)
mlp_2_r = recall_score(y_test, prediction2)
mlp_2_f = f1_score(y_test, prediction2)

In [26]:
mlp_2

0.782608695652174

In [27]:
mlp3 = MLPClassifier(hidden_layer_sizes = (32, 32, 32))
mlp3.fit(X_train, y_train)
accuracy3 = mlp3.score(X_test, y_test)
prediction3 = mlp3.predict(X_test)
mlp_3 = accuracy_score(y_test, prediction3)
mlp_3_p = precision_score(y_test, prediction3)
mlp_3_r = recall_score(y_test, prediction3)
mlp_3_f = f1_score(y_test, prediction3)

In [28]:
mlp_3

0.7753623188405797

In [29]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [30]:
y_pred = classifier.predict(X_test)
ly_pred = list(y_pred)
print(ly_pred)
print()
ly_test = list(y_test)
print(ly_test)

correct_pred = sum([ 1 for (x,y) in zip(ly_pred, ly_test) if x==y])
print(correct_pred)
accuracy = correct_pred / len(ly_test)
nb = accuracy
nb_p = precision_score(y_test, y_pred)
nb_r = recall_score(y_test, y_pred)
nb_f = f1_score(y_test, y_pred)

[1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1]

[1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0

In [31]:
accuracy

0.8152173913043478

In [32]:
data = {'Estimators':['K-Nearest Nrighborhood with K=3',
                      'K-Nearest Nrighborhood with K=7',
                      'K-Nearest Nrighborhood with K=11',
                      'Multi Layer Perception with 1 Hidden Layer',
                      'Multi Layer Perception with 2 Hidden Layer',
                      'Multi Layer Perception with 3 Hidden Layer',
                      'Gaussian Naive Bayes',
                     ],
        'Accuracy':[knn3, knn7, knn11, mlp_1, mlp_2, mlp_3, nb],
        'Precision':[knn3_p, knn7_p, knn11_p, mlp_1_p, mlp_2_p, mlp_3_p, nb_p],
        'Recall':[knn3_r, knn7_r, knn11_r, mlp_1_r, mlp_2_r, mlp_3_r, nb_r],
        'F1_Score':[knn3_f, knn7_f, knn11_f, mlp_1_f, mlp_2_f, mlp_3_f, nb_f],
       }
data = pd.DataFrame(data)
data

Estimators  Accuracy  Precision    Recall  \
0             K-Nearest Nrighborhood with K=3  0.775362   0.837037  0.738562   
1             K-Nearest Nrighborhood with K=7  0.807971   0.873134  0.764706   
2            K-Nearest Nrighborhood with K=11  0.844203   0.904412  0.803922   
3  Multi Layer Perception with 1 Hidden Layer  0.818841   0.893130  0.764706   
4  Multi Layer Perception with 2 Hidden Layer  0.782609   0.803922  0.803922   
5  Multi Layer Perception with 3 Hidden Layer  0.775362   0.779141  0.830065   
6                        Gaussian Naive Bayes  0.815217   0.875000  0.777778   

   F1_Score  
0  0.784722  
1  0.815331  
2  0.851211  
3  0.823944  
4  0.803922  
5  0.803797  
6  0.823529